### ISSUE TITLE
Without Stepping?

### ISSUE THREAD

**Issue by BedrettinOrtak** [RooRoo6080/Trailblazer-AndroidHikingTracker#4]
Is it possible to make such a map on a moving vehicle without stepping? i was wondering about this

**Comment by RooRoo6080** [comment]
The only other in-built sensor on a phone that can technically measure distance data is the accelerometer.
I actually tried to use it when first making this app, but I found that it's extremely inaccurate.
Here's a Google tech talk on why: https://youtu.be/C7JQ7Rpwn2k.
It's technically possible but is near impossible to implement so I wouldn't recommend it.

**Comment by BedrettinOrtak** [comment]
Is it not possible to get results using additional sensors?

**Comment by RooRoo6080** [comment]
Not that I know of
